# Generated by Django 4.0.1 on 2022-01-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование товара ')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание товара')),
                ('category', models.CharField(choices=[('cosmetic', 'Косметика'), ('clothes', 'Одежда'), ('other', 'Разное')], default='other', max_length=2000, verbose_name='Категория')),
                ('remnant', models.IntegerField(verbose_name='Остаток')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name_plural': 'Электронный магазин',
                'db_table': 'el_shop',
            },
        ),
    ]
